<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ImGui.NET" Version="1.89.9.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MiniEngine.Core\MiniEngine.Core.csproj" />
    <ProjectReference Include="..\MiniEngine.Drivers.Vulkan\MiniEngine.Drivers.Vulkan.csproj" PrivateAssets="compile" />
  </ItemGroup>

</Project>
