<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net7.0</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SixLabors.ImageSharp" Version="3.0.2" />
    <PackageReference Include="YamlDotNet" Version="13.7.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MiniEngine.Core\MiniEngine.Core.csproj" />
  </ItemGroup>

</Project>