<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net7.0-windows</TargetFramework>
    <Nullable>disable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>disable</ImplicitUsings>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MiniEngine.AssetManager\MiniEngine.AssetManager.csproj" />
    <ProjectReference Include="..\MiniEngine.Rendering.OpenGL\MiniEngine.Rendering.OpenGL.csproj" />
    <ProjectReference Include="..\MiniEngine.Rendering.Vulkan\MiniEngine.Rendering.Vulkan.csproj" />
    <ProjectReference Include="..\MiniEngine\MiniEngine.csproj" />
  </ItemGroup>

</Project>