<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
	<Nullable>disable</Nullable>
	<ImplicitUsings>disable</ImplicitUsings>
	<AllowUnsafeBlocks>True</AllowUnsafeBlocks>
	<RootNamespace>MiniEngine</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Materials\mat_unlit_color.asset" />
    <None Remove="Resources\MeshSphere.mtl" />
    <None Remove="Resources\MeshSphere.obj" />
    <None Remove="Resources\PixelAqua.bmp" />
    <None Remove="Resources\PixelMagenta.bmp" />
    <None Remove="Resources\PixelWhite.bmp" />
    <None Remove="Shaders\render_structs.glsl" />
    <None Remove="Shaders\Unlit.frag" />
    <None Remove="Shaders\Unlit.vert" />
    <None Remove="Shaders\unlit_color.asset" />
    <None Remove="Shaders\unlit_color.frag" />
    <None Remove="Shaders\vertex_layout.glsl" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Materials\mat_unlit_color.asset" />
    <EmbeddedResource Include="Resources\MeshSphere.mtl" />
    <EmbeddedResource Include="Resources\MeshSphere.obj" />
    <EmbeddedResource Include="Resources\PixelAqua.bmp" />
    <EmbeddedResource Include="Resources\PixelMagenta.bmp" />
    <EmbeddedResource Include="Resources\PixelWhite.bmp" />
    <EmbeddedResource Include="Shaders\unlit_color.asset" />
    <EmbeddedResource Include="Shaders\unlit_color.frag" />
    <EmbeddedResource Include="Shaders\vertex_layout.glsl" />
    <EmbeddedResource Include="Shaders\render_structs.glsl" />
    <EmbeddedResource Include="Shaders\unlit.frag" />
    <EmbeddedResource Include="Shaders\unlit.vert" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AssimpNet" Version="5.0.0-beta1" />
    <PackageReference Include="ImGui.NET" Version="1.89.9.3" />
    <PackageReference Include="SixLabors.ImageSharp" Version="3.0.2" />
	<PackageReference Include="YamlDotNet" Version="13.7.1" />
  </ItemGroup>

</Project>
