<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net7.0-windows</TargetFramework>
    <Nullable>disable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>disable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ImGui.NET" Version="1.89.9.3" />
    <PackageReference Include="SixLabors.ImageSharp" Version="3.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MiniEngine.Drivers.Vulkan\MiniEngine.Drivers.Vulkan.csproj" />
    <ProjectReference Include="..\MiniEngine.Presentations.Glfw\MiniEngine.Presentations.Glfw.csproj" />
    <ProjectReference Include="..\MiniEngine.Rendering.Vulkan\MiniEngine.Rendering.Vulkan.csproj" />
    <ProjectReference Include="..\MiniEngine\MiniEngine.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Shaders\" />
  </ItemGroup>

</Project>