/* Please note that this file is generated by the VulkanSharp's generator. Do not edit directly.

   Licensed under the MIT license.

   Copyright 2016 Xamarin Inc

   This notice may not be removed from any source distribution.
   See LICENSE file for licensing details.
*/

using System;

namespace MiniEngine.Drivers.Vulkan
{

	
    /// <summary>
    /// Vulkan CommandPool
    /// </summary>
    public partial class VkCommandPool : INonDispatchableHandleMarshalling
    {
        internal VkCommandPool() { }

        internal UInt64 m;

        UInt64 INonDispatchableHandleMarshalling.Handle
        {
            get
            {
                return m;
            }
        }
    }

	public partial class VkBuffer : INonDispatchableHandleMarshalling
	{
		internal VkBuffer() {}

		internal UInt64 m;

		UInt64 INonDispatchableHandleMarshalling.Handle {
			get {
				return m;
			}
		}
	}

	public partial class VkBufferView : INonDispatchableHandleMarshalling
	{
		internal VkBufferView() {}

		internal UInt64 m;

		UInt64 INonDispatchableHandleMarshalling.Handle {
			get {
				return m;
			}
		}
	}

	public partial class VkImage : INonDispatchableHandleMarshalling
	{
		internal VkImage() {}

		internal UInt64 m;

		UInt64 INonDispatchableHandleMarshalling.Handle {
			get {
				return m;
			}
		}
	}

	public partial class VkImageView : INonDispatchableHandleMarshalling
	{
		internal VkImageView() {}

		internal UInt64 m;

		UInt64 INonDispatchableHandleMarshalling.Handle {
			get {
				return m;
			}
		}
	}

	public partial class VkShaderModule : INonDispatchableHandleMarshalling
	{
		internal VkShaderModule() {}

		internal UInt64 m;

		UInt64 INonDispatchableHandleMarshalling.Handle {
			get {
				return m;
			}
		}
	}

	public partial class VkPipeline : INonDispatchableHandleMarshalling
	{
		internal VkPipeline() {}

		internal UInt64 m;

		UInt64 INonDispatchableHandleMarshalling.Handle {
			get {
				return m;
			}
		}
	}

	public partial class VkPipelineLayout : INonDispatchableHandleMarshalling
	{
		internal VkPipelineLayout() {}

		internal UInt64 m;

		UInt64 INonDispatchableHandleMarshalling.Handle {
			get {
				return m;
			}
		}
	}

	public partial class VkSampler : INonDispatchableHandleMarshalling
	{
		internal VkSampler() {}

		internal UInt64 m;

		UInt64 INonDispatchableHandleMarshalling.Handle {
			get {
				return m;
			}
		}
	}

	public partial class VkDescriptorSet : INonDispatchableHandleMarshalling
	{
		internal VkDescriptorSet() {}

		internal UInt64 m;

		UInt64 INonDispatchableHandleMarshalling.Handle {
			get {
				return m;
			}
		}
	}

	public partial class VkDescriptorSetLayout : INonDispatchableHandleMarshalling
	{
		internal VkDescriptorSetLayout() {}

		internal UInt64 m;

		UInt64 INonDispatchableHandleMarshalling.Handle {
			get {
				return m;
			}
		}
	}

	public partial class VkDescriptorPool : INonDispatchableHandleMarshalling
	{
		internal VkDescriptorPool() {}

		internal UInt64 m;

		UInt64 INonDispatchableHandleMarshalling.Handle {
			get {
				return m;
			}
		}
	}

	public partial class VkFence : INonDispatchableHandleMarshalling
	{
		internal VkFence() {}

		internal UInt64 m;

		UInt64 INonDispatchableHandleMarshalling.Handle {
			get {
				return m;
			}
		}
	}

	public partial class VkSemaphore : INonDispatchableHandleMarshalling
	{
		internal VkSemaphore() {}

		internal UInt64 m;

		UInt64 INonDispatchableHandleMarshalling.Handle {
			get {
				return m;
			}
		}
	}

	public partial class VkEvent : INonDispatchableHandleMarshalling
	{
		internal VkEvent() {}

		internal UInt64 m;

		UInt64 INonDispatchableHandleMarshalling.Handle {
			get {
				return m;
			}
		}
	}

	public partial class VkQueryPool : INonDispatchableHandleMarshalling
	{
		internal VkQueryPool() {}

		internal UInt64 m;

		UInt64 INonDispatchableHandleMarshalling.Handle {
			get {
				return m;
			}
		}
	}

	public partial class VkFramebuffer : INonDispatchableHandleMarshalling
	{
		internal VkFramebuffer() {}

		internal UInt64 m;

		UInt64 INonDispatchableHandleMarshalling.Handle {
			get {
				return m;
			}
		}
	}

	public partial class VkRenderPass : INonDispatchableHandleMarshalling
	{
		internal VkRenderPass() {}

		internal UInt64 m;

		UInt64 INonDispatchableHandleMarshalling.Handle {
			get {
				return m;
			}
		}
	}

	public partial class VkPipelineCache : INonDispatchableHandleMarshalling
	{
		internal VkPipelineCache() {}

		internal UInt64 m;

		UInt64 INonDispatchableHandleMarshalling.Handle {
			get {
				return m;
			}
		}
	}

	public partial class VkObjectTableNvx : INonDispatchableHandleMarshalling
	{
		internal VkObjectTableNvx() {}

		internal UInt64 m;

		UInt64 INonDispatchableHandleMarshalling.Handle {
			get {
				return m;
			}
		}
	}

	public partial class VkIndirectCommandsLayoutNvx : INonDispatchableHandleMarshalling
	{
		internal VkIndirectCommandsLayoutNvx() {}

		internal UInt64 m;

		UInt64 INonDispatchableHandleMarshalling.Handle {
			get {
				return m;
			}
		}
	}

	public partial class VkDescriptorUpdateTemplateKhr : INonDispatchableHandleMarshalling
	{
		internal VkDescriptorUpdateTemplateKhr() {}

		internal UInt64 m;

		UInt64 INonDispatchableHandleMarshalling.Handle {
			get {
				return m;
			}
		}
	}

	public partial class VkSamplerYcbcrConversionKhr : INonDispatchableHandleMarshalling
	{
		internal VkSamplerYcbcrConversionKhr() {}

		internal UInt64 m;

		UInt64 INonDispatchableHandleMarshalling.Handle {
			get {
				return m;
			}
		}
	}

	public partial class VkValidationCacheExt : INonDispatchableHandleMarshalling
	{
		internal VkValidationCacheExt() {}

		internal UInt64 m;

		UInt64 INonDispatchableHandleMarshalling.Handle {
			get {
				return m;
			}
		}
	}

	public partial class VkDisplayKhr : INonDispatchableHandleMarshalling
	{
		internal VkDisplayKhr() {}

		internal UInt64 m;

		UInt64 INonDispatchableHandleMarshalling.Handle {
			get {
				return m;
			}
		}
	}

	public partial class VkDisplayModeKhr : INonDispatchableHandleMarshalling
	{
		internal VkDisplayModeKhr() {}

		internal UInt64 m;

		UInt64 INonDispatchableHandleMarshalling.Handle {
			get {
				return m;
			}
		}
	}

	public partial class VkSurfaceKhr : INonDispatchableHandleMarshalling
	{
		internal VkSurfaceKhr() {}

		internal UInt64 m;

		UInt64 INonDispatchableHandleMarshalling.Handle {
			get {
				return m;
			}
		}
	}

	public partial class VkSwapchainKhr : INonDispatchableHandleMarshalling
	{
		internal VkSwapchainKhr() {}

		internal UInt64 m;

		UInt64 INonDispatchableHandleMarshalling.Handle {
			get {
				return m;
			}
		}
	}

	public partial class VkDebugReportCallbackExt : INonDispatchableHandleMarshalling
	{
		internal VkDebugReportCallbackExt() {}

		internal UInt64 m;

		UInt64 INonDispatchableHandleMarshalling.Handle {
			get {
				return m;
			}
		}
	}
}
