/* Please note that this file is generated by the VulkanSharp's generator. Do not edit directly.

   Licensed under the MIT license.

   Copyright 2016 Xamarin Inc

   This notice may not be removed from any source distribution.
   See LICENSE file for licensing details.
*/

using System;

namespace MiniEngine.Drivers.Vulkan
{

	
    

	public partial class Buffer : INonDispatchableHandleMarshalling
	{
		internal Buffer() {}

		internal UInt64 m;

		UInt64 INonDispatchableHandleMarshalling.Handle {
			get {
				return m;
			}
		}
	}

	public partial class BufferView : INonDispatchableHandleMarshalling
	{
		internal BufferView() {}

		internal UInt64 m;

		UInt64 INonDispatchableHandleMarshalling.Handle {
			get {
				return m;
			}
		}
	}

	public partial class Image : INonDispatchableHandleMarshalling
	{
		internal Image() {}

		internal UInt64 m;

		UInt64 INonDispatchableHandleMarshalling.Handle {
			get {
				return m;
			}
		}
	}

	public partial class ImageView : INonDispatchableHandleMarshalling
	{
		internal ImageView() {}

		internal UInt64 m;

		UInt64 INonDispatchableHandleMarshalling.Handle {
			get {
				return m;
			}
		}
	}

	public partial class ShaderModule : INonDispatchableHandleMarshalling
	{
		internal ShaderModule() {}

		internal UInt64 m;

		UInt64 INonDispatchableHandleMarshalling.Handle {
			get {
				return m;
			}
		}
	}

	public partial class Pipeline : INonDispatchableHandleMarshalling
	{
		internal Pipeline() {}

		internal UInt64 m;

		UInt64 INonDispatchableHandleMarshalling.Handle {
			get {
				return m;
			}
		}
	}

	public partial class PipelineLayout : INonDispatchableHandleMarshalling
	{
		internal PipelineLayout() {}

		internal UInt64 m;

		UInt64 INonDispatchableHandleMarshalling.Handle {
			get {
				return m;
			}
		}
	}

	public partial class Sampler : INonDispatchableHandleMarshalling
	{
		internal Sampler() {}

		internal UInt64 m;

		UInt64 INonDispatchableHandleMarshalling.Handle {
			get {
				return m;
			}
		}
	}

	public partial class DescriptorSet : INonDispatchableHandleMarshalling
	{
		internal DescriptorSet() {}

		internal UInt64 m;

		UInt64 INonDispatchableHandleMarshalling.Handle {
			get {
				return m;
			}
		}
	}

	public partial class DescriptorSetLayout : INonDispatchableHandleMarshalling
	{
		internal DescriptorSetLayout() {}

		internal UInt64 m;

		UInt64 INonDispatchableHandleMarshalling.Handle {
			get {
				return m;
			}
		}
	}

	public partial class DescriptorPool : INonDispatchableHandleMarshalling
	{
		internal DescriptorPool() {}

		internal UInt64 m;

		UInt64 INonDispatchableHandleMarshalling.Handle {
			get {
				return m;
			}
		}
	}

	

	public partial class Event : INonDispatchableHandleMarshalling
	{
		internal Event() {}

		internal UInt64 m;

		UInt64 INonDispatchableHandleMarshalling.Handle {
			get {
				return m;
			}
		}
	}

	public partial class QueryPool : INonDispatchableHandleMarshalling
	{
		internal QueryPool() {}

		internal UInt64 m;

		UInt64 INonDispatchableHandleMarshalling.Handle {
			get {
				return m;
			}
		}
	}

	public partial class Framebuffer : INonDispatchableHandleMarshalling
	{
		internal Framebuffer() {}

		internal UInt64 m;

		UInt64 INonDispatchableHandleMarshalling.Handle {
			get {
				return m;
			}
		}
	}


	public partial class PipelineCache : INonDispatchableHandleMarshalling
	{
		internal PipelineCache() {}

		internal UInt64 m;

		UInt64 INonDispatchableHandleMarshalling.Handle {
			get {
				return m;
			}
		}
	}

	public partial class ObjectTableNvx : INonDispatchableHandleMarshalling
	{
		internal ObjectTableNvx() {}

		internal UInt64 m;

		UInt64 INonDispatchableHandleMarshalling.Handle {
			get {
				return m;
			}
		}
	}

	public partial class IndirectCommandsLayoutNvx : INonDispatchableHandleMarshalling
	{
		internal IndirectCommandsLayoutNvx() {}

		internal UInt64 m;

		UInt64 INonDispatchableHandleMarshalling.Handle {
			get {
				return m;
			}
		}
	}

	public partial class DescriptorUpdateTemplateKhr : INonDispatchableHandleMarshalling
	{
		internal DescriptorUpdateTemplateKhr() {}

		internal UInt64 m;

		UInt64 INonDispatchableHandleMarshalling.Handle {
			get {
				return m;
			}
		}
	}

	public partial class SamplerYcbcrConversionKhr : INonDispatchableHandleMarshalling
	{
		internal SamplerYcbcrConversionKhr() {}

		internal UInt64 m;

		UInt64 INonDispatchableHandleMarshalling.Handle {
			get {
				return m;
			}
		}
	}

	public partial class ValidationCacheExt : INonDispatchableHandleMarshalling
	{
		internal ValidationCacheExt() {}

		internal UInt64 m;

		UInt64 INonDispatchableHandleMarshalling.Handle {
			get {
				return m;
			}
		}
	}

	public partial class DisplayKhr : INonDispatchableHandleMarshalling
	{
		internal DisplayKhr() {}

		internal UInt64 m;

		UInt64 INonDispatchableHandleMarshalling.Handle {
			get {
				return m;
			}
		}
	}

	public partial class DisplayModeKhr : INonDispatchableHandleMarshalling
	{
		internal DisplayModeKhr() {}

		internal UInt64 m;

		UInt64 INonDispatchableHandleMarshalling.Handle {
			get {
				return m;
			}
		}
	}

	public partial class SurfaceKhr : INonDispatchableHandleMarshalling
	{
		public SurfaceKhr() {}

       
        public UInt64 Handle;

		UInt64 INonDispatchableHandleMarshalling.Handle {
			get {
				return Handle;
			}
		}
	}

	public partial class SwapchainKhr : INonDispatchableHandleMarshalling
	{
		internal SwapchainKhr() {}

		internal UInt64 m;

		UInt64 INonDispatchableHandleMarshalling.Handle {
			get {
				return m;
			}
		}
	}

	public partial class DebugReportCallbackExt : INonDispatchableHandleMarshalling
	{
		internal DebugReportCallbackExt() {}

		internal UInt64 m;

		UInt64 INonDispatchableHandleMarshalling.Handle {
			get {
				return m;
			}
		}
	}
}
