/* Please note that this file is generated by the VulkanSharp's generator. Do not edit directly.

   Licensed under the MIT license.

   Copyright 2016 Xamarin Inc

   This notice may not be removed from any source distribution.
   See LICENSE file for licensing details.
*/

using MiniEngine.Drivers.Vulkan.Interop;
using MiniEngine.Drivers.Vulkan.Windows;
using System;
using System.Runtime.InteropServices;

namespace MiniEngine.Drivers.Vulkan
{
	public partial class VkInstance
	{
        public VkSurfaceKhr CreateWin32SurfaceKHR(Win32SurfaceCreateInfoKhr pCreateInfo, AllocationCallbacks pAllocator = null)
        {
            Result result;
            VkSurfaceKhr pSurface;
            unsafe
            {
                pSurface = new VkSurfaceKhr();

                fixed (UInt64* ptrpSurface = &pSurface.m)
                {
                    result = NativeMethods.vkCreateWin32SurfaceKHR(m, pCreateInfo != null ? pCreateInfo.m : (MiniEngine.Drivers.Vulkan.Interop.Windows.Win32SurfaceCreateInfoKhr*)default(IntPtr), pAllocator != null ? pAllocator.m : null, ptrpSurface);
                }
                if (result != Result.Success)
                    throw new ResultException(result);

                return pSurface;
            }
        }
    }
}
