//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniEngine.Ressources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MiniEngine.Ressources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PixelMagenta {
            get {
                object obj = ResourceManager.GetObject("PixelMagenta", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PixelWhite {
            get {
                object obj = ResourceManager.GetObject("PixelWhite", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #version 450
        ///
        ///layout(binding = 1) uniform sampler2D texSampler;
        ///
        ///layout(location = 0) in vec3 fragColor;
        ///layout(location = 1) in vec2 fragTexCoord;
        ///
        ///layout(location = 0) out vec4 outColor;
        ///
        ///
        ///void main() {
        ///    //outColor = vec4(fragColor, 1.0);
        ///    outColor = texture(texSampler, fragTexCoord);
        ///}.
        /// </summary>
        internal static string UnlitFrag {
            get {
                return ResourceManager.GetString("UnlitFrag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #version 450
        ///
        /////push constants block
        ///layout( push_constant ) uniform constants
        ///{
        ///	mat4 render_matrix;
        ///} PushConstants;
        ///
        ///
        ///layout(location = 0) in vec3 inPosition;
        ///layout(location = 1) in vec3 inColor;
        ///layout(location = 2) in vec2 inTexCoord;
        ///
        ///layout(location = 0) out vec3 fragColor;
        ///layout(location = 1) out vec2 fragTexCoord;
        ///
        ///void main() {
        ///    gl_Position = PushConstants.render_matrix * vec4(inPosition, 1.0);
        ///    
        ///    fragColor = inColor;
        ///    fragTexCoord = inTexCoord;
        ///}.
        /// </summary>
        internal static string UnlitVert {
            get {
                return ResourceManager.GetString("UnlitVert", resourceCulture);
            }
        }
    }
}
