<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Resources\glfw3.dll" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\glfw3.dll" />
  </ItemGroup>

</Project>
