#version 450
#extension GL_EXT_nonuniform_qualifier : enable

//-----------------------
//Structs
struct scene_data
{
    mat4 matrix_vp;
    vec3 camera_location;
};

struct object_instance_data
{
    vec3 location;
    vec3 rotation;
    vec3 scale;
    mat4 transform_matrix;
};

struct meshlet_instance_data
{
    uint object_index;
    uint meshlet_index;
    uint texture_index;
    uint draw_calls_buffer_index;
    uint draw_call_index;
    uint visible;
};

struct draw_call
{
    uint index_count;
    uint instance_count;
    uint first_index;
    uint vertex_offsset;
    uint first_instance;
};


//-----------------------
//Bindings
layout(binding = 1) readonly uniform _scene {
    scene_data scene;
};
layout(binding = 2) buffer _draw_calls_buffers {
    draw_call calls[]; 
} draw_calls[];

layout(std430, binding = 3) readonly buffer _objects {
    object_instance_data objects[];
};
layout(std430, binding = 4) buffer _meshlet_instances {
    meshlet_instance_data meshlet_instances[];
};


//-----------------------
//Compute config
layout (local_size_x = 1, local_size_y = 1, local_size_z = 1) in;


//-----------------------
//Main
void main()
{
	uint meshlet_instance_index = gl_GlobalInvocationID.x;
	uint object_index = meshlet_instances[meshlet_instance_index].object_index;
    uint draw_buffer_index = meshlet_instances[meshlet_instance_index].draw_calls_buffer_index;
    uint draw_call_index = meshlet_instances[meshlet_instance_index].draw_call_index;

    uint visible = 1;

    if(scene.camera_location.x < 0)
    {
        if(objects[object_index].location.x > 0)
        {
            visible = 0;
        }
    }
    else
    {
        if(objects[object_index].location.x < 0)
        {
            visible = 0;
        }
    }

    draw_calls[draw_buffer_index].calls[draw_call_index].instance_count = visible;
    meshlet_instances[meshlet_instance_index].visible = visible;

}