#version 450
#extension GL_EXT_nonuniform_qualifier : enable

#include "../../MiniEngine.Core/Resources/Shaders/render_structs.glsl"

//-----------------------
//Structs




//-----------------------
//Bindings
layout(binding = 1) readonly uniform _scene {
    scene_data scene;
};
layout(binding = 2) buffer _draw_calls_buffers {
    draw_call calls[]; 
} draw_calls[];

layout(std430, binding = 3) readonly buffer _objects {
    object_instance_data objects[];
};
layout(std430, binding = 4) buffer _meshlet_instances {
    meshlet_instance_data meshlet_instances[];
};


//-----------------------
//Compute config
layout (local_size_x = 1, local_size_y = 1, local_size_z = 1) in;


//-----------------------
//Main
void main()
{
	uint meshlet_instance_index = gl_GlobalInvocationID.x;
	uint object_index = meshlet_instances[meshlet_instance_index].object_index;
    uint draw_buffer_index = meshlet_instances[meshlet_instance_index].draw_calls_buffer_index;
    uint draw_call_index = meshlet_instances[meshlet_instance_index].draw_call_index;

    uint visible = 1;

    if(scene.camera_location.x < 0)
    {
        if(objects[object_index].location.x > 0)
        {
            visible = 0;
        }
    }
    else
    {
        if(objects[object_index].location.x < 0)
        {
            visible = 0;
        }
    }

    draw_calls[draw_buffer_index].calls[draw_call_index].instance_count = visible;
    meshlet_instances[meshlet_instance_index].visible = visible;

}