#version 450
#extension GL_EXT_nonuniform_qualifier : enable
#extension GL_KHR_shader_subgroup_ballot: enable

#include "../../MiniEngine.Core/Resources/Shaders/render_structs.glsl"

//-----------------------
//Structs




//-----------------------
//Bindings
layout(binding = 1) readonly uniform _scene {
    scene_data scene;
};
layout(binding = 2) buffer _draw_calls_buffers {
    draw_call calls[]; 
} draw_calls[];

layout(binding = 3) readonly buffer _objects {
    object_instance_data objects[];
};
layout(binding = 4) buffer _meshlet_instances {
    meshlet_instance_data meshlet_instances[];
};
layout(binding = 5) buffer _meshlets {
    meshlet_data meshlets[];
};
layout(binding = 6) buffer _draw_calls_counts {
    uint draw_calls_counts[];
};


//-----------------------
//Compute config
layout (local_size_x = 256, local_size_y = 1, local_size_z = 1) in;


uint is_visible(uint object_index)
{
	//grab sphere cull data from the object buffer
    //the technique is very simple, the viewprojection matrix is already set to return coords between -1 and 1 on x and y axis when divided by w (depth in opengl/vulkan)
    //so we just redo here what the vertex shader and the rasterizer will do and check if the object is on screen using the radius
    vec4 sphereBounds = vec4(objects[object_index].location, 1);
	
    vec4 center4 = scene.matrix_vp * sphereBounds;
    vec3 center = center4.xyz / center4.w;

    if(center.x < -1.0 || center.x > 1.0)
        return 0;
    if(center.y < -1.0 || center.y > 1.0)
        return 0;
    if(center.z < 0 || center.z > 1)
        return 0;
//
//	float radius = 0.1f;
//
//    //frustrum culling
//	if(center.z * scene.frustum_right - abs(center.x) * scene.frustum_left <= -radius)
//        return 0;
//
//    //frustrum culling
//    if(center.z * scene.frustum_bottom - abs(center.y) * scene.frustum_top <= -radius)
//        return 0;
//	
//	// the near/far plane culling uses camera space Z directly
//    if(center.z + radius <= scene.znear || center.z - radius >= scene.zfar)
//        return 0;

	return 1;
}

//-----------------------
//Main
void main()
{
	uint meshlet_instance_index = gl_GlobalInvocationID.x;
    

    if(meshlet_instance_index >= scene.nb_meshlet_instances)
        return;

    
	uint object_index = meshlet_instances[meshlet_instance_index].object_index;
    uint draw_buffer_index = meshlet_instances[meshlet_instance_index].draw_calls_buffer_index;
    uint meshlet_index = meshlet_instances[meshlet_instance_index].meshlet_index;

    uint visible = is_visible(object_index);
//
//    if(scene.camera_location.x < 0)
//    {
//        if(objects[object_index].location.x > 0)
//        {
//            visible = 0;
//        }
//    }
//    else
//    {
//        if(objects[object_index].location.x < 0)
//        {
//            visible = 0;
//        }
//    }

    //visible = 1;

    meshlet_instances[meshlet_instance_index].visible = visible;
    draw_calls[draw_buffer_index].calls[meshlet_instances[meshlet_instance_index].draw_call_index].instance_count = visible;

//    draw_calls_counts[draw_buffer_index]++;
//    uint draw_call_index = draw_calls_counts[draw_buffer_index];
//
//    draw_calls[draw_buffer_index].calls[draw_call_index].index_count = meshlets[meshlet_index].nb_indices;
//    draw_calls[draw_buffer_index].calls[draw_call_index].instance_count = 1;
//    draw_calls[draw_buffer_index].calls[draw_call_index].first_index = meshlets[meshlet_index].indices_buffer_index;
//    draw_calls[draw_buffer_index].calls[draw_call_index].vertex_offset = meshlets[meshlet_index].vertices_buffer_index;
//    draw_calls[draw_buffer_index].calls[draw_call_index].first_instance = meshlet_instance_index;
//
//    //draw_call_index++;
//    draw_calls_counts[draw_buffer_index] = draw_call_index;

}